name: ci

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1.0
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v3
      name: Build & push Docker image
      with:
        image: bulk-downloader
        tags: latest
        registry: rg.fnt.work:5000
        dockerfile: Dockerfile
