name: ci

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - id: package_version
        run: echo $(jq -r .version package.json)

      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: bulk-downloader
          tag: ${{ steps.package_version.outputs }}
          registry: rg.fr-par.scw.cloud/fntwork
          dockerfile: Dockerfile
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
