name: ci

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Get NodeJS package info
        id: get_package_info
        run: echo "::set-output name=version::$(jq -r .version package.json)"

      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: bulk-downloader
          tag: "${{ steps.get_package_info.outputs.version }}"
          registry: ${{ secrets.REGISTRY_URI }}
          dockerfile: Dockerfile
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
